# -*- coding: utf-8 -*-
"""Terror-Forge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyaOYKMFSmLbmAtKPRZ6B2NwGO3MDcUO
"""

# BLOCK 1: Setup + Google Drive Connection
#
#
# Installs dependencies
#
#
# - yt-dlp: for downloading audio from YouTube
# - pydub + ffmpeg: for audio trimming and conversion
# - pyannote.audio: for speaker diarization and overlap detection

!pip install --quiet --upgrade pip
!pip install --quiet librosa ffmpeg pydub yt-dlp
!pip install --quiet git+https://github.com/pyannote/pyannote-audio.git
!apt-get -qq install ffmpeg

#  Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

#  Libraries
import os
import sys
import tempfile
import subprocess
import logging
import traceback
from pathlib import Path
import shutil


# Audio / Diarization Libraries
from pyannote.core import Segment
from pydub import AudioSegment
from pydub.silence import detect_nonsilent
from pyannote.core import Timeline
from pyannote.audio import Pipeline




# Google Drive Output Folder
print("Mounting Google Drive...")
drive_export_path = Path("/content/drive/MyDrive/YouTubeAudio")
drive_export_path.mkdir(parents=True, exist_ok=True)

if drive_export_path.exists():
    print(" Google Drive mounted successfully!")
    print(f" Folder for audio output is ready: {drive_export_path}\n")
else:
    print("ERROR: Failed to access or create the export folder in Google Drive.")

# BLOCK 2: Hugging Face Token Setup + Logger
# Prompts the user to enter their Hugging Face access token.
# Also sets up structured logging across the notebook.

from getpass import getpass

# Prompt for token
HUGGINGFACE_TOKEN = getpass("Enter your Hugging Face token:")

# Logger setup
def setup_logger(log_level=logging.INFO, log_to_file=False, log_file_path="diarization_log.txt"):
    """
    Sets up a global logger for the notebook.

    Args:
        log_level (int): Logging level, e.g., logging.INFO or logging.DEBUG.
        log_to_file (bool): Whether to also log to a file.
        log_file_path (str): Path to the log file (if log_to_file is True).

    Returns:
        Logger object.
    """
    logger = logging.getLogger("diarization_logger")
    logger.setLevel(log_level)

    # Avoid duplicate handlers in Colab reruns
    if not logger.handlers:
        formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')

        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setFormatter(formatter)
        logger.addHandler(console_handler)

        if log_to_file:
            file_handler = logging.FileHandler(log_file_path)
            file_handler.setFormatter(formatter)
            logger.addHandler(file_handler)

    return logger

# Initialize logger
logger = setup_logger()
logger.info("Logger initialized and ready.")

# Confirm token was entered
if not HUGGINGFACE_TOKEN:
    raise ValueError("Hugging Face token not provided. Please run this cell again and enter it.")

# BLOCK 3: Utility Functions


# - download_audio(): Downloads the best audio stream from a YouTube URL (ignores playlists).
# - convert_audio(): Converts .webm to .wav without forcing 48kHz — preserves original sample rate, but enforces mono channel.
# - trim_and_normalize(): Removes leading/trailing silence and normalizes volume.
# - get_youtube_title(): Gets a clean title from the video for use in filenames.
# - chunk_and_export(): Splits audio into chunks and uploads to Google Drive.


def download_audio(url: str, output_path: str):
    logger.info(f" Starting download for: {url}")
    try:
        result = subprocess.run(
            ["yt-dlp", "--no-playlist", "-f", "bestaudio", "-o", output_path, url],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        if result.returncode != 0:
            logger.error(f" yt-dlp stderr:\n{result.stderr}")
            raise subprocess.CalledProcessError(result.returncode, result.args)

        logger.info(f"Audio downloaded to: {output_path}")
    except subprocess.CalledProcessError:
        logger.error(f"yt-dlp failed to download: {url}", exc_info=True)
        raise

def convert_audio(input_path: str, output_path: str):
    """
    Convert downloaded audio to WAV format using ffmpeg.
    Keeps the original sample rate, forces mono channel. Overwrites if file exists.
    """
    logger.info(f"🎧 Converting {input_path} → {output_path} (preserving sample rate)")
    try:
        result = subprocess.run(
            ["ffmpeg", "-y", "-i", input_path, "-ac", "1", output_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True
        )
        logger.info("Conversion complete")
    except subprocess.CalledProcessError as e:
        logger.error(f"ffmpeg conversion failed for: {input_path}", exc_info=True)
        logger.error(f"ffmpeg stderr:\n{e.stderr}")
        raise

def trim_and_normalize(wav_path: str):
    logger.info(f"Trimming and normalizing audio: {wav_path}")
    try:
        audio = AudioSegment.from_wav(wav_path)
        nonsilent_ranges = detect_nonsilent(audio, min_silence_len=500, silence_thresh=-40)

        if not nonsilent_ranges:
            logger.warning("No nonsilent audio found. Skipping trimming.")
            return

        start_trim = nonsilent_ranges[0][0]
        end_trim = nonsilent_ranges[-1][1]
        trimmed_audio = audio[start_trim:end_trim]

        change_in_dBFS = -trimmed_audio.max_dBFS
        normalized_audio = trimmed_audio.apply_gain(change_in_dBFS)
        normalized_audio.export(wav_path, format="wav")
        logger.info(f"Audio trimmed and normalized: {wav_path}")

    except Exception:
        logger.error(f"Error while trimming/normalizing: {wav_path}", exc_info=True)
        raise

def get_youtube_title(url: str) -> str:
    logger.info(f"Getting title for: {url}")
    try:
        result = subprocess.run(
            ["yt-dlp", "--no-playlist", "--get-title", url],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True
        )
        title = result.stdout.strip().replace(" ", "_")
        logger.info(f"Title extracted: {title}")
        return title
    except subprocess.CalledProcessError:
        logger.warning("Could not extract title, using fallback.")
        return None

def chunk_and_export(wav_path: str, speaker_label: str = "unknown", user_tag: str = ""):
    logger.info(f"Exporting chunk for speaker: {speaker_label}")
    try:
        base_output_path = "/content/drive/MyDrive/YouTubeAudio"
        os.makedirs(base_output_path, exist_ok=True)

        audio = AudioSegment.from_wav(wav_path)
        sample_rate = audio.frame_rate
        filename = Path(wav_path).stem

        # Prepend user-defined tag if provided
        tag = f"{user_tag}_" if user_tag else ""
        output_path = f"{base_output_path}/{tag}{filename}_{speaker_label}_{sample_rate}Hz.wav"

        # Export to temp file first
        with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as tmpfile:
            audio.export(tmpfile.name, format="wav")

        # Move to final destination
        shutil.move(tmpfile.name, output_path)
        logger.info(f"Uploaded chunk to Google Drive: {output_path}")

    except Exception:
        logger.error(f"Failed to export chunk: {wav_path}", exc_info=True)
        raise

# BLOCK 4: Load Diarization Pipelines

# Loads speaker diarization and (optionally) overlapped speech detection models from Hugging Face.
# If the OSD model fails to load, diarization will still run without overlap filtering.


logger.info("Loading diarization and overlap detection models...")

try:
    diarization_pipeline = Pipeline.from_pretrained(
        "pyannote/speaker-diarization",
        use_auth_token=HUGGINGFACE_TOKEN
    )
    logger.info("Diarization model loaded.")

    try:
        osd_pipeline = Pipeline.from_pretrained(
            "pyannote/overlapped-speech-detection",
            use_auth_token=HUGGINGFACE_TOKEN
        )
        logger.info("Overlap detection model loaded.")
    except Exception:
        osd_pipeline = None
        logger.warning("OSD model not loaded. Overlapping speech will NOT be filtered.")

except Exception:
    logger.error("Failed to load diarization pipeline — cannot continue.", exc_info=True)
    raise  # hard fail if diarization model doesn't load

# BLOCK 5: Main Processing Engine — YouTube to Clean Speaker Segments

# MANUAL INPUTS


MIDDLE_SEGMENT_DURATION = 400  # Duration in seconds to diarize (e.g. 300 = 5 min)
CUSTOM_LABEL = "ACME CEO"  # Add a custom name tag to appear in output filenames

# URL(s) to process
YOUTUBE_URLS = [
    "https://www.youtube.com/watch?v=A-k8X6qlM40",
    ""  # PUT THE LINKS HERE ITS HEREEEE I WRITE THIS SO ITS EASY TO SEEE
]

logger.info(f"📏 Will extract and process middle {MIDDLE_SEGMENT_DURATION} seconds of each clip.")

# Main Processing Loop
for url_index, url in enumerate(YOUTUBE_URLS):
    logger.info(f"\n🗕️ Processing URL {url_index+1}/{len(YOUTUBE_URLS)}")

    # Extract YouTube video title
    title = get_youtube_title(url)
    if not title:
        logger.warning("Could not extract title from YouTube URL.")
        continue

    webm_path = f"audio_{url_index}.webm"
    wav_path = f"audio_{url_index}.wav"

    # Download and convert audio
    logger.info(f"Downloading best audio from: {url}")
    try:
        download_audio(url, webm_path)
    except Exception:
        logger.error(f"Failed to download audio from: {url}", exc_info=True)
        continue

    logger.info(f"Converting {webm_path} to WAV (mono, same sample rate)")
    convert_audio(webm_path, wav_path)

    # Extract the middle segment (user-defined) before any preprocessing
    logger.info("Extracting middle segment of audio for processing and diarization")
    audio = AudioSegment.from_wav(wav_path)
    total_duration = len(audio) / 1000
    middle_start = max(0, (total_duration - MIDDLE_SEGMENT_DURATION) / 2)
    middle_end = middle_start + MIDDLE_SEGMENT_DURATION
    start_ms = int(middle_start * 1000)
    end_ms = int(middle_end * 1000)
    middle_audio = audio[start_ms:end_ms]

    # Export the middle segment to a temp WAV file
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as middle_wav_file:
        middle_audio.export(middle_wav_file.name, format="wav")
        middle_wav_path = middle_wav_file.name

    # Trim silence and normalize only the middle segment
    logger.info("Trimming silence and normalizing middle segment")
    trim_and_normalize(middle_wav_path)

    # Run diarization and handle speaker-separated segments
    logger.info("Running diarization and saving speaker-separated files...")
    try:
        diarization = diarization_pipeline(middle_wav_path)
        diarized_segments = list(diarization.itertracks(yield_label=True))

        # Overlapped speech detection
        if osd_pipeline:
            osd = osd_pipeline(middle_wav_path)
            osd_timeline = osd.get_timeline()
            logger.info("Overlap detection applied.")
        else:
            osd_timeline = Timeline(segments=[])
            logger.info("No overlap detection — using all segments.")

        # Filter segments to remove overlap and short clips
        fused_segments = []
        for turn, _, speaker in diarized_segments:
            segment = Segment(turn.start, turn.end)
            clean_parts = Timeline([segment]).extrude(osd_timeline)
            for clean_segment in clean_parts:
                if (clean_segment.end - clean_segment.start) >= 3.0:
                    fused_segments.append((clean_segment, speaker))

        logger.info(f"Usable (non-overlapping) segments: {len(fused_segments)}")

        # Export each speaker chunk
        for segment, speaker in fused_segments:
            try:
                start_ms = int(float(segment.start) * 1000)
                end_ms = int(float(segment.end) * 1000)
            except Exception:
                logger.warning("Skipping segment due to cast error", exc_info=True)
                continue

            # Defensive check to avoid slicing beyond audio length
            if end_ms > len(middle_audio):
                logger.warning(f"Segment end {end_ms}ms exceeds audio length {len(middle_audio)}ms — skipping.")
                continue

            segment_audio = middle_audio[start_ms:end_ms]

            with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmpfile:
                segment_audio.export(tmpfile.name, format="wav")
                chunk_and_export(tmpfile.name, speaker, user_tag=CUSTOM_LABEL)
                os.unlink(tmpfile.name)

        # Clean up temp middle WAV
        os.unlink(middle_wav_path)

    except Exception:
        logger.error("Diarization failed. Proceeding with full audio export.", exc_info=True)
        chunk_and_export(wav_path, speaker_label="unknown", user_tag=CUSTOM_LABEL)

logger.info("All YouTube URLs have been processed!")